/* CRIAÇÃO DO MODELO FISICO A PARTIR DO MODELO LÓGICO 01*/

SHOW DATABASES; -- Mostra todos os bancos criados por você no SQL

CREATE DATABASE COMERCIO;

USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE, 
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)	
);

/* ENDERECO - OBRIGATORIO
CADASTRO DE SOMENTE UM.

TELEFONE - NAO OBRIGATORIO
CADASTRO DE MAIS DE UM (OPCIONAL) /*

/* O PRIMARY KEY É UMA COLUNA, OU CONJUNTO DE COLUNAS QUE
 IDENTIFICA DE FORMA UNICA CADA REGISTRO EM UMA TABELA .
 
O AUTO_INCREMENT É UMA PROPRIEDADE USADA PARA GERAR VALORES
ÚNICOS AUTOMATICAMENTE PARA UMA COLUNA EM UMA TABELA (GERALMENTE 
É USADA COM A PRIMARY KEY).
ISSO FACILITA A CRIAÇÃO DE VALORES INCREMENTAIS PARA CADA NOVA LINHA
INSERIDA NA TABELA, SEM A NECESSIDADE DE DEFINIR MANUALMENTE OS VALORES.

NOT NULL SIGNIFICA QUE O CAMPO DEVE SER OBRIGATORIAMENTE PREENCHIDO, OU
SEJA SEM VALOR NULO.

UNIQUE SIGNIFICA QUE É UM VALOR QUE CADA INDIVIDUO TEM, OU SEJA NAO PODE 
SER UMA INFORMAÇÃO REPETIDA.
/*

/*
CHAVE ESTRANGEIRA É A CHAVE PRIMÁRIA DE UMA TABELA QUE VAI ATÉ A OUTRA TABELA 
PARA FAZER REFERENCIA ENTRE REGISTROS */

DESC CLIENTE; --SABER OS TIPOS DE VALOR NA TABELA