CREATE TABLE LIVROS(
	NOME_DO_LIVRO VARCHAR(30),
	NOME_DO_AUTOR VARCHAR(30),
	SEXO_DO_AUTOR CHAR(1),
	NÚMERO_DE_PÁGINAS INT,
	NOME_DA_EDITORA VARCHAR(30),
	VALOR_DO_LIVRO FLOAT,
	ESTADO_DA_EDITORA VARCHAR(2),
	ANO_DA_PUBLICAÇÃO INT

); 

/* EXEMPLO BASE DE COMO INSERIR UM REGISTRO NAS COLUNAS */

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUE('JOAO','M', 'JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',997774856);

/*FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
						('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
						
/* ATIVIDADE 1*/

INSERT INTO LIVROS VALUES('Cavaleiro Real', 'Ana Claudia', 'F', 465, 'Atlas', 49.90, 'RJ', 2009),
						('Sql para leigos', 'João Nunes', 'M', 450, 'Addison', 98.00, 'SP', 2018),
						('Receitas Cadeiras', 'Celia Tavares', 'F', 210, 'Atlas', 45.00, 'RJ', 2008),
						('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', 2018),
						('Habitos Saudáveis', 'Eduardo Santos', 'M', 630, 'Beta', 150.98, 'RJ', 2019),
						('A Casa Marrom', 'Hermes Macedo', 'M', 250, 'Bubba', 60.00, 'MG', 2016),
						('Estacio Querido', 'Geraldo Francisco', 'M', 310, 'Insignia', 100.00, 'ES', 2016),
						('Pra sempre amigas', 'Leda Silva', 'F', 510, 'Insignia', 78.98, 'ES', 2011),
						('Copas Inesqueciveis', 'Marco Alcantara', 'M', 200, 'Larson', 130.98, 'RS', 2018),
						('O poder da mente', 'Clara Mafra', 'F', 120, 'Continental', 56.58, 'RS', 2017);
						
/* EXERCICIO 1*/

SELECT * FROM LIVROS;

/* EXERCICIO 2*/	

SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;

/* EXERCICO 3*/ 

SELECT NOME_DO_LIVRO, ESTADO_DA_EDITORA FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M';

/* EXERCICIO 4*/

SELECT NOME_DO_LIVRO, NÚMERO_DE_PÁGINAS FROM LIVROS
WHERE SEXO_DO_AUTOR = 'F';

/* EXERCICIO 5*/

SELECT VALOR_DO_LIVRO FROM LIVROS
WHERE ESTADO_DA_EDITORA = 'SP';

/* EXERCICIO 6*/

SELECT NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NÚMERO_DE_PÁGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_DA_PUBLICAÇÃO FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M'
AND (ESTADO_DA_EDITORA = 'SP' OR ESTADO_DA_EDITORA = 'RJ');

  					