/* ATIVIDADE 4 */

/* EXERCICIO 1 
RELATÓRIO GERAL DE TODOS OS CLIENTES 
*/

DESC CLIENTE;

DESC ENDERECO;

DESC TELEFONE;

/* CLIENTE - IDCLIENTE / NOME / SEXO / EMAIL / CPF

ENDERECO - IDENDERECO / RUA / BAIRRO / CIDADE / ESTADO / ID_CLIENTE

TELEFONE - IDTELEFONE / TIPO / NUMERO / ID_CLIENTE

*/

SELECT CLIENTE.NOME, CLIENTE.SEXO, CLIENTE.EMAIL, CLIENTE.CPF, ENDERECO.RUA, ENDERECO.BAIRRO, ENDERECO.CIDADE, ENDERECO.ESTADO, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
	INNER JOIN ENDERECO
	ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
	INNER JOIN TELEFONE
	ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

-- OUTRA SOLUÇÃO USANDO PONTEIRAMENTO

SELECT C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE;

/* 12 13 18 19 
CORRIGIR UM REGISTRO DESSES IDS 
*/

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 12
OR IDCLIENTE = 13
OR IDCLIENTE = 18
OR IDCLIENTE =19; 

UPDATE CLIENTE SET SEXO = 'F'
WHERE IDCLIENTE = 12
OR IDCLIENTE = 13
OR IDCLIENTE = 18
OR IDCLIENTE = 19;

SELECT * FROM CLIENTE
WHERE IDCLIENTE IN (12, 13. 18, 19)

UPDATE CLIENTE SET SEXO = 'F'
WHERE IDCLIENTE IN (12, 13, 18, 19)

UPDATE CLIENTE SET SEXO = 'M'
WHERE IDCLIENTE = 16;

/* EXERCICIO 2
RELATORIO DE HOMENS 
*/

SELECT C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'M';


/* EXERCICIO 3
RELATORIO DE MULHERES 
*/

SELECT C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO, T.TIPO, T.NUMERO
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
WHERE SEXO = 'F';

/* EXERCICIO 4
QUANTIDADE DE HOMENS E MULHERES
*/

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;

/* IDS E EMAIL DAS MULHERER
QUE MOREM NO CENTRO DO RIO DE JANEIRO E NAO TENHAM CELULAR
*/ 

SELECT IDCLIENTE, EMAIL 
FROM CLIENTE C
	INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
	INNER JOIN TELEFONE T
	ON C.IDCLIENTE = T.ID_CLIENTE
WHERE BAIRRO = "CENTRO"
AND ESTADO = "RJ"
AND TIPO != "CEL";